server:
  build: .
  volumes:
    - .:/app
    - /app/node_modules
  links:
    - mongodb
  command: ./zenbot.sh trade GDAX.eth-usd --paper --enable_profit_stop_pct=10, --profit_stop_pct=4, trend_ema=36, and --sell_rate=-0.006
  restart: always

mongodb:
  image: mongo:latest
  volumes_from:
    - mongodb-data
  command: mongod --smallfiles

mongodb-data:
  image: mongo:latest
  volumes:
    - ./data/db:/data/db
  command: "true"
